# Discord-REPRAM Bridge Configuration

# Discord Bot Configuration
discord:
  token: "YOUR_DISCORD_BOT_TOKEN"
  channel_id: "YOUR_DISCORD_CHANNEL_ID"
  guild_id: "YOUR_DISCORD_GUILD_ID"

# REPRAM Configuration
repram:
  nodes:
    - "http://YOUR_GCP_EXTERNAL_IP:8081"
    - "http://YOUR_GCP_EXTERNAL_IP:8082"
    - "http://YOUR_GCP_EXTERNAL_IP:8083"
  default_ttl: 3600  # 1 hour default TTL
  min_ttl: 300       # 5 minutes minimum TTL
  max_ttl: 604800    # 1 week maximum TTL

# Bridge Settings
bridge:
  # Message prefix for Discord messages synced from REPRAM
  repram_prefix: "🌐"
  
  # Message prefix for Discord messages synced to REPRAM
  discord_prefix: "💬"
  
  # Show TTL in Discord messages
  show_ttl: true
  
  # TTL display format
  ttl_format: "⏰ %s"
  
  # Key embedding in Discord messages (hidden)
  embed_keys: true
  
  # Poll interval for checking REPRAM messages (seconds)
  poll_interval: 10
  
  # Cleanup interval for expired messages (seconds)
  cleanup_interval: 60

# TTL Command Configuration
ttl_commands:
  # Enable TTL prefix commands like "/ttl60 Hello"
  enabled: true
  
  # Command prefix
  prefix: "/ttl"
  
  # Allowed TTL ranges
  min_ttl: 300     # 5 minutes
  max_ttl: 604800  # 1 week
  
  # Default TTL if not specified
  default_ttl: 3600  # 1 hour

# Logging Configuration
logging:
  level: "info"  # debug, info, warn, error
  file: "bridge.log"
  
# Performance Settings
performance:
  max_concurrent_requests: 10
  request_timeout: 30  # seconds
  retry_attempts: 3
  retry_delay: 5  # seconds