version: '3.8'

services:
  # REPRAM Cluster Node 1
  node1:
    build:
      context: .
      dockerfile: Dockerfile
      target: cluster-node
    ports:
      - "8081:8080"
      - "9091:9090"
    environment:
      - REPRAM_NODE_ID=node1
      - NODE_ADDRESS=node1
      - REPRAM_PORT=8080
      - REPRAM_GOSSIP_PORT=9090
      - REPRAM_BOOTSTRAP_PEERS=node2:8080,node3:8080
      - REPRAM_REPLICATION_FACTOR=1
    networks:
      - cluster-net

  # REPRAM Cluster Node 2
  node2:
    build:
      context: .
      dockerfile: Dockerfile
      target: cluster-node
    ports:
      - "8082:8080"
      - "9092:9090"
    environment:
      - REPRAM_NODE_ID=node2
      - NODE_ADDRESS=node2
      - REPRAM_PORT=8080
      - REPRAM_GOSSIP_PORT=9090
      - REPRAM_BOOTSTRAP_PEERS=node1:8080,node3:8080
      - REPRAM_REPLICATION_FACTOR=1
    networks:
      - cluster-net

  # REPRAM Cluster Node 3
  node3:
    build:
      context: .
      dockerfile: Dockerfile
      target: cluster-node
    ports:
      - "8083:8080"
      - "9093:9090"
    environment:
      - REPRAM_NODE_ID=node3
      - NODE_ADDRESS=node3
      - REPRAM_PORT=8080
      - REPRAM_GOSSIP_PORT=9090
      - REPRAM_BOOTSTRAP_PEERS=node1:8080,node2:8080
      - REPRAM_REPLICATION_FACTOR=1
    networks:
      - cluster-net

networks:
  cluster-net:
    driver: bridge