version: '3.8'

services:
  repram-cluster-0:
    image: repram:latest
    command: ["./repram-cluster-node"]
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - REPRAM_PORT=8080
      - REPRAM_GOSSIP_PORT=9090
      - REPRAM_NODE_ID=node0
      - REPRAM_LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  repram-cluster-1:
    image: repram:latest
    command: ["./repram-cluster-node"]
    ports:
      - "8081:8080"
      - "9091:9090"
    environment:
      - REPRAM_PORT=8080
      - REPRAM_GOSSIP_PORT=9090
      - REPRAM_NODE_ID=node1
      - REPRAM_LOG_LEVEL=info
      - REPRAM_BOOTSTRAP_PEERS=repram-cluster-0:9090
    depends_on:
      - repram-cluster-0
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  repram-cluster-2:
    image: repram:latest
    command: ["./repram-cluster-node"]
    ports:
      - "8082:8080"
      - "9092:9090"
    environment:
      - REPRAM_PORT=8080
      - REPRAM_GOSSIP_PORT=9090
      - REPRAM_NODE_ID=node2
      - REPRAM_LOG_LEVEL=info
      - REPRAM_BOOTSTRAP_PEERS=repram-cluster-0:9090,repram-cluster-1:9090
    depends_on:
      - repram-cluster-0
      - repram-cluster-1
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  default:
    driver: bridge
