#!/usr/bin/env bash
# Re-sign the omega root list every 25 minutes and update dnsmasq.
#
# Spec: docs/internal/REPRAM-2.1-Minimal-BurnIn.md, "Setup" section
# (signed list `exp` = 30 min; republish every 25 min).
#
# Run on the observer:
#   PRIVATE_KEY=~/.repram-burnin/omega.priv \
#   NODES=10.0.20.72:9090,10.0.10.81:9090,10.0.10.104:9090 \
#   DNSMASQ_HOSTS_FILE=/etc/dnsmasq.d/repram-burnin.conf \
#   ./test/burnin/sign-loop.sh
#
# Stops on Ctrl-C. Each cycle: sign, write dnsmasq config, restart dnsmasq,
# log success/failure with a timestamp.
#
# REQUIRES passwordless sudo for `systemctl restart dnsmasq` and write
# access to $DNSMASQ_HOSTS_FILE. SIGHUP doesn't re-read txt-record entries,
# so a full restart is the only reliable way to publish a new signed list.
# Add to /etc/sudoers.d/repram-burnin:
#   <user> ALL=(root) NOPASSWD: /bin/systemctl restart dnsmasq, /bin/systemctl reload dnsmasq, /usr/bin/tee /etc/dnsmasq.d/repram-burnin.conf*

set -uo pipefail

private_key="${PRIVATE_KEY:?PRIVATE_KEY (path to omega.priv) must be set}"
nodes="${NODES:?NODES (comma-sep host:gossip-port list) must be set}"
dnsmasq_file="${DNSMASQ_HOSTS_FILE:?DNSMASQ_HOSTS_FILE must be set}"
expires_in="${EXP_DURATION:-30m}"
interval_sec="${REPUBLISH_INTERVAL_SEC:-1500}"  # 25 min
bootstrap_target="${BOOTSTRAP_TARGET:-_omega.repram.io}"

repo_root=$(git -C "$(dirname "$0")" rev-parse --show-toplevel)
omega_bin="$repo_root/bin/repram-omega"

if [[ ! -x "$omega_bin" ]]; then
    echo "$(date -Is) building $omega_bin" >&2
    (cd "$repo_root" && make build-omega)
fi

trap 'echo "$(date -Is) sign-loop stopped"; exit 0' INT TERM

cycle=0
while :; do
    cycle=$((cycle + 1))

    txt_value=$("$omega_bin" sign \
        --key "$private_key" \
        --expires-in "$expires_in" \
        --nodes "$nodes" 2>/tmp/sign-loop.err) || {
        echo "$(date -Is) cycle=$cycle SIGN-FAIL: $(cat /tmp/sign-loop.err)" >&2
        sleep 30
        continue
    }

    # Write the two TXT records dnsmasq serves. Use sudo tee so the file
    # in /etc/dnsmasq.d/ can be owned by root.
    if ! sudo -n tee "$dnsmasq_file" >/dev/null <<EOF
# Generated by sign-loop.sh — burn-in cycle $cycle at $(date -Is)
txt-record=_bootstrap.repram.io,"omega=${bootstrap_target}"
txt-record=${bootstrap_target},"${txt_value}"
EOF
    then
        echo "$(date -Is) cycle=$cycle WRITE-FAIL: cannot write $dnsmasq_file (passwordless sudo for tee required)" >&2
        sleep 30
        continue
    fi

    # dnsmasq SIGHUP only re-reads /etc/hosts and lease files — NOT
    # txt-record entries from the main conf or conf-dir. We have to do a
    # full restart for the new signed list to take effect. The restart is
    # sub-second; in-flight queries get retried by clients.
    if ! sudo -n systemctl restart dnsmasq 2>/dev/null; then
        echo "$(date -Is) cycle=$cycle WARN: dnsmasq restart failed — needs passwordless sudo for systemctl restart dnsmasq" >&2
    fi

    echo "$(date -Is) cycle=$cycle OK published=${bootstrap_target} (${expires_in})"
    sleep "$interval_sec"
done
