{{- if eq .Values.mode "single" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "repram.fullname" . }}-single
  labels:
    {{- include "repram.labels" . | nindent 4 }}
    app.kubernetes.io/component: single-node
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "repram.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: single-node
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "repram.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: single-node
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "repram.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./repram-node"]
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          env:
            - name: REPRAM_PORT
              value: "{{ .Values.config.port }}"
            - name: REPRAM_LOG_LEVEL
              value: "{{ .Values.config.logLevel }}"
            - name: REPRAM_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REPRAM_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}