apiVersion: v1
kind: ConfigMap
metadata:
  name: repram-config
  namespace: repram
  labels:
    app.kubernetes.io/name: repram
    app.kubernetes.io/component: config
data:
  # Node configuration
  REPRAM_PORT: "8080"
  REPRAM_GOSSIP_PORT: "9090"
  REPRAM_LOG_LEVEL: "info"
  REPRAM_MAX_REQUEST_SIZE: "10485760"  # 10MB
  REPRAM_RATE_LIMIT: "100"             # requests per second per IP
  REPRAM_RATE_BURST: "200"             # burst limit
  REPRAM_CLEANUP_INTERVAL: "30s"
  REPRAM_METRICS_INTERVAL: "15s"
  
  # Security settings
  REPRAM_SECURITY_ENABLED: "true"
  REPRAM_TIMEOUT: "30s"
  
  # Cluster configuration
  REPRAM_REPLICATION_FACTOR: "3"
  REPRAM_QUORUM_SIZE: "2"