apiVersion: v1
kind: Namespace
metadata:
  name: repram
  labels:
    name: repram
    app.kubernetes.io/name: repram
    app.kubernetes.io/part-of: repram-network
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: repram-service-account
  namespace: repram
  labels:
    app.kubernetes.io/name: repram
    app.kubernetes.io/component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: repram-role
  namespace: repram
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: repram-role-binding
  namespace: repram
subjects:
- kind: ServiceAccount
  name: repram-service-account
  namespace: repram
roleRef:
  kind: Role
  name: repram-role
  apiGroup: rbac.authorization.k8s.io