version: '3.8'

services:
  # Single container running multiple REPRAM nodes
  # This simulates how Flux would deploy multiple instances
  flux-sim:
    build:
      context: ..
      dockerfile: Dockerfile.flux-sim
    container_name: repram-flux-sim
    environment:
      - DISCOVERY_DOMAIN=localhost  # In real Flux: fade.repram.io
      - BASE_PORT=8081
      - MAX_PORTS=5
      - NODE_COUNT=3               # Run 3 nodes in this container
      - REPLICATION_FACTOR=3
    ports:
      # Expose all possible ports
      - "8081:8081"
      - "8082:8082" 
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      # Gossip ports
      - "9081:9081"
      - "9082:9082"
      - "9083:9083"
      - "9084:9084"
      - "9085:9085"
    volumes:
      - /tmp/repram-flux-sim:/tmp

  # Optional: Fade server that discovers nodes dynamically
  fade-server:
    build:
      context: ..
      dockerfile: Dockerfile.fade
    container_name: fade-flux-sim
    environment:
      - PORT=3000
      # Instead of hardcoding nodes, fade could also implement discovery
      - FADE_NODES=http://flux-sim:8081,http://flux-sim:8082,http://flux-sim:8083
    ports:
      - "3000:3000"
    depends_on:
      - flux-sim
    profiles:
      - with-fade