version: '3.8'

services:
  repram-node-1:
    build:
      context: ../../
      dockerfile: Dockerfile
      target: cluster-node
    container_name: repram-node-1
    environment:
      - REPRAM_NODE_ID=node-1
      - NODE_ADDRESS=repram-node-1
      - REPRAM_PORT=8081
      - REPRAM_GOSSIP_PORT=9091
      - REPLICATION_FACTOR=3
      - REPRAM_BOOTSTRAP_PEERS=repram-node-2:9092,repram-node-3:9093
    ports:
      - "8081:8081"
      - "9091:9091"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - repram-cluster

  repram-node-2:
    build:
      context: ../../
      dockerfile: Dockerfile
      target: cluster-node
    container_name: repram-node-2
    environment:
      - REPRAM_NODE_ID=node-2
      - NODE_ADDRESS=repram-node-2
      - REPRAM_PORT=8082
      - REPRAM_GOSSIP_PORT=9092
      - REPLICATION_FACTOR=3
      - REPRAM_BOOTSTRAP_PEERS=repram-node-1:9091,repram-node-3:9093
    ports:
      - "8082:8082"
      - "9092:9092"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - repram-cluster
    depends_on:
      - repram-node-1

  repram-node-3:
    build:
      context: ../../
      dockerfile: Dockerfile
      target: cluster-node
    container_name: repram-node-3
    environment:
      - REPRAM_NODE_ID=node-3
      - NODE_ADDRESS=repram-node-3
      - REPRAM_PORT=8083
      - REPRAM_GOSSIP_PORT=9093
      - REPLICATION_FACTOR=3
      - REPRAM_BOOTSTRAP_PEERS=repram-node-1:9091,repram-node-2:9092
    ports:
      - "8083:8083"
      - "9093:9093"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - repram-cluster
    depends_on:
      - repram-node-1
      - repram-node-2

networks:
  repram-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16