version: '3.8'

services:
  # Fade node 1 (using raw node)
  fade-node-1:
    build: ..
    command: ["./repram-node-raw"]
    ports:
      - "8080:8080"  # HTTP API
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - fade-network

  # Fade node 2 (using raw node)
  fade-node-2:
    build: ..
    command: ["./repram-node-raw"]
    ports:
      - "8081:8080"  # HTTP API
    environment:
      - PORT=8080
    depends_on:
      fade-node-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - fade-network

  # Fade node 3 (using raw node)
  fade-node-3:
    build: ..
    command: ["./repram-node-raw"]
    ports:
      - "8082:8080"  # HTTP API
    environment:
      - PORT=8080
    depends_on:
      fade-node-1:
        condition: service_healthy
      fade-node-2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - fade-network

  # Fade web UI proxy server
  fade-web:
    build: 
      context: ..
      dockerfile: Dockerfile.fade
    ports:
      - "3000:3000"  # Web UI
    environment:
      - FADE_NODES=http://fade-node-1:8080,http://fade-node-2:8080,http://fade-node-3:8080
    depends_on:
      fade-node-1:
        condition: service_healthy
      fade-node-2:
        condition: service_healthy
      fade-node-3:
        condition: service_healthy
    networks:
      - fade-network

networks:
  fade-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16