version: '3.8'

# This simulates what would happen in Flux:
# - 3 cluster nodes with gossip replication  
# - 3 fade servers all proxying to the same nodes
# We need to test if this configuration works properly

services:
  # === CLUSTER NODES ===
  # Fade cluster node 1 (seed node)
  fade-node-1:
    image: repram-cluster-node:local
    ports:
      - "8080:8080"  # HTTP API
      - "9090:9090"  # Gossip protocol
    environment:
      - REPRAM_PORT=8080
      - REPRAM_GOSSIP_PORT=9090
      - REPRAM_NODE_ID=fade-node-1
      - NODE_ADDRESS=fade-node-1
      - REPLICATION_FACTOR=3
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - fade-network

  # Fade cluster node 2 (bootstrap from node 1)
  fade-node-2:
    image: repram-cluster-node:local
    ports:
      - "8081:8080"  # HTTP API
      - "9091:9090"  # Gossip protocol
    environment:
      - REPRAM_PORT=8080
      - REPRAM_GOSSIP_PORT=9090
      - REPRAM_NODE_ID=fade-node-2
      - NODE_ADDRESS=fade-node-2
      - REPLICATION_FACTOR=3
      - REPRAM_BOOTSTRAP_PEERS=fade-node-1:8080
    depends_on:
      fade-node-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - fade-network

  # Fade cluster node 3 (bootstrap from node 1)
  fade-node-3:
    image: repram-cluster-node:local
    ports:
      - "8082:8080"  # HTTP API
      - "9092:9090"  # Gossip protocol
    environment:
      - REPRAM_PORT=8080
      - REPRAM_GOSSIP_PORT=9090
      - REPRAM_NODE_ID=fade-node-3
      - NODE_ADDRESS=fade-node-3
      - REPLICATION_FACTOR=3
      - REPRAM_BOOTSTRAP_PEERS=fade-node-1:8080
    depends_on:
      fade-node-1:
        condition: service_healthy
      fade-node-2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - fade-network

  # === FADE SERVERS (simulating Flux scenario) ===
  # Fade web server 1 - all point to same nodes
  fade-web-1:
    image: fade-server:local
    environment:
      - FADE_NODES=http://fade-node-1:8080,http://fade-node-2:8080,http://fade-node-3:8080
      - PORT=3000
    ports:
      - "3000:3000"  # Web UI
    depends_on:
      fade-node-1:
        condition: service_healthy
      fade-node-2:
        condition: service_healthy
      fade-node-3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - fade-network

  # Fade web server 2 - same configuration as server 1
  fade-web-2:
    image: fade-server:local
    environment:
      - FADE_NODES=http://fade-node-1:8080,http://fade-node-2:8080,http://fade-node-3:8080
      - PORT=3000
    ports:
      - "3010:3000"  # Different external port
    depends_on:
      fade-node-1:
        condition: service_healthy
      fade-node-2:
        condition: service_healthy
      fade-node-3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - fade-network

  # Fade web server 3 - same configuration as server 1 & 2
  fade-web-3:
    image: fade-server:local
    environment:
      - FADE_NODES=http://fade-node-1:8080,http://fade-node-2:8080,http://fade-node-3:8080
      - PORT=3000
    ports:
      - "3020:3000"  # Different external port
    depends_on:
      fade-node-1:
        condition: service_healthy
      fade-node-2:
        condition: service_healthy
      fade-node-3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - fade-network

networks:
  fade-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16