version: '3.8'

services:
  # Home node - runs independently, no bootstrap peers needed
  home-node:
    build:
      context: ..
      dockerfile: Dockerfile
      target: cluster-node
    container_name: repram-home-node
    ports:
      - "8080:8080"  # HTTP API
      - "9090:9090"  # Gossip protocol
    environment:
      - REPRAM_NODE_ID=home-node
      - NODE_ADDRESS=home-node
      - REPRAM_PORT=8080
      - REPRAM_GOSSIP_PORT=9090
      - REPLICATION_FACTOR=3
      # No REPRAM_BOOTSTRAP_PEERS - this node starts first
    networks:
      - repram-network
    volumes:
      - /tmp/repram-home:/tmp/repram

networks:
  repram-network:
    name: repram-global-network
    driver: bridge