name: Build and Push Docker Images

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  FADE_SERVER_IMAGE: ticktockbent/fade-server
  CLUSTER_NODE_IMAGE: ticktockbent/repram-cluster-node

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract metadata for fade-server
      id: meta-fade
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.FADE_SERVER_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Extract metadata for cluster-node
      id: meta-cluster
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.CLUSTER_NODE_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push fade-server
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.fade
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta-fade.outputs.tags }}
        labels: ${{ steps.meta-fade.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push cluster-node
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        target: cluster-node
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta-cluster.outputs.tags }}
        labels: ${{ steps.meta-cluster.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run fade-server security scan
      if: github.event_name != 'pull_request'
      uses: docker/scout-action@v1
      with:
        command: cves
        image: ${{ env.FADE_SERVER_IMAGE }}:latest
        only-severities: critical,high
        exit-code: true

    - name: Run cluster-node security scan
      if: github.event_name != 'pull_request'
      uses: docker/scout-action@v1
      with:
        command: cves
        image: ${{ env.CLUSTER_NODE_IMAGE }}:latest
        only-severities: critical,high
        exit-code: true